[2025-01-29T20:33:32.075+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T20:33:32.095+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.primera_tarea manual__2025-01-29T20:33:16.528254+00:00 [queued]>
[2025-01-29T20:33:32.103+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MI_PRIMER_DAG.primera_tarea manual__2025-01-29T20:33:16.528254+00:00 [queued]>
[2025-01-29T20:33:32.103+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2025-01-29T20:33:32.238+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): primera_tarea> on 2025-01-29 20:33:16.528254+00:00
[2025-01-29T20:33:32.256+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'MI_PRIMER_DAG', 'primera_tarea', 'manual__2025-01-29T20:33:16.528254+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp9u4e3k97']
[2025-01-29T20:33:32.254+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-29T20:33:32.260+0000] {standard_task_runner.py:72} INFO - Started process 102 to run task
[2025-01-29T20:33:32.259+0000] {standard_task_runner.py:105} INFO - Job 16: Subtask primera_tarea
[2025-01-29T20:33:32.307+0000] {task_command.py:467} INFO - Running <TaskInstance: MI_PRIMER_DAG.primera_tarea manual__2025-01-29T20:33:16.528254+00:00 [running]> on host f807a3f6dc0a
[2025-01-29T20:33:32.380+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='MI_PRIMER_DAG' AIRFLOW_CTX_TASK_ID='primera_tarea' AIRFLOW_CTX_EXECUTION_DATE='2025-01-29T20:33:16.528254+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-29T20:33:16.528254+00:00'
[2025-01-29T20:33:32.382+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-29T20:33:32.382+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-29T20:33:32.383+0000] {logging_mixin.py:190} INFO - Current task name:primera_tarea state:running start_date:2025-01-29 20:33:32.096140+00:00
[2025-01-29T20:33:32.383+0000] {logging_mixin.py:190} INFO - Dag name:MI_PRIMER_DAG and current dag run status:running
[2025-01-29T20:33:32.384+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T20:33:32.384+0000] {python.py:240} INFO - Done. Returned value was: Â¡Hola, mundo! 10
[2025-01-29T20:33:32.402+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T20:33:32.403+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=MI_PRIMER_DAG, task_id=primera_tarea, run_id=manual__2025-01-29T20:33:16.528254+00:00, execution_date=20250129T203316, start_date=20250129T203332, end_date=20250129T203332
[2025-01-29T20:33:32.413+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-29T20:33:32.413+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-29T20:33:32.414+0000] {logging_mixin.py:190} INFO - Dag name:MI_PRIMER_DAG queued_at:2025-01-29 20:33:16.559021+00:00
[2025-01-29T20:33:32.414+0000] {logging_mixin.py:190} INFO - Task hostname:f807a3f6dc0a operator:PythonOperator
[2025-01-29T20:33:32.439+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T20:33:32.460+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-29T20:33:32.462+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
